### ISSUE TITLE
When a scalingstate is specified, that doesn't exist. The Operator will scale to some other state

### ISSUE THREAD

**Issue by PathogenDE** [ContainerSolutions/pre-scaling-operator#79]
To reproduce:

1. Place cssd and css (in bau).
2.  Place scalingstate in peak mode. 
3. Change scalingstate to a non-existant-state e.g. "idontexist".

The operator will scale to bau. 

The error is logged but due it is not handled in the reconciler in a way where the reconciler would terminate. 
Intended behaviour?
See line 268 in reconciler.go

**Comment by andreas131989** [comment]
I think we don't validate the states at the moment, so we could have unintended behaviour when stats are wrong, absent etc.

One way to mitigate this, is to create an admission webhook in the operator itself, that will validate each CRD. Essentially, it will be able to compare a ss/css state with those present in cssd for example and exit gracefully before we even reach the reconciler.
